project_id = "vwzeewpizvdgvuvqjsbv"

[functions.validate-guest]
verify_jwt = false

[functions.guest-data]
verify_jwt = false

[functions.update-guest-info]
verify_jwt = false

[functions.validate-admin]
verify_jwt = false

[functions.admin-manage]
verify_jwt = false

[functions.customer-data]
verify_jwt = false

[functions.validate-employee]
verify_jwt = false

[functions.validate-session]
verify_jwt = false

[functions.get-view-settings]
verify_jwt = false
